# Adjust this Makefile to suit your server and project requirements.

PROJ_ROOT=${HOME}/mysite

# The MakoFW location:
MAKOFW_DIR=${PROJ_ROOT}/makofw

# The 'input' and 'build' directories:
IN_DIR=${PROJ_ROOT}/input
BUILD_DIR=${PROJ_ROOT}/build

# The publication locations:
OUT_DEV=${PROJ_ROOT}/output/dev
OUT_PROD=${PROJ_ROOT}/output/prod

# The python binary to use:
PYTHON=python2.7
export PYTHONPATH:=${MAKOFW_DIR}/lib/python:${PYTHONPATH}


# By default, publish to the development site:
dev: inputToBuild
	MAKOFW_BUILD_MODE=dev ${PYTHON} ${MAKOFW_DIR}/bin/publish.py "${BUILD_DIR}" "${OUT_DEV}"

# Publish to the development site without doing as many ACL checks:
fast: inputToBuild
	MAKOFW_BUILD_MODE=dev ACL_CHECK=0 ${PYTHON} ${MAKOFW_DIR}/bin/publish.py "${BUILD_DIR}" "${OUT_DEV}"

# Publish to the production site:
prod: inputToBuild
	MAKOFW_BUILD_MODE=prod ${PYTHON} ${MAKOFW_DIR}/bin/publish.py "${BUILD_DIR}" "${OUT_PROD}"

# Touch some critical files that force the whole site to be rebuilt:
touch:
	touch ${IN_DIR}/_master.tmpl

# Useful for local development:
devserver:
	cd "${OUT_DEV}"; ${PYTHON} -m SimpleHTTPServer

# Copy 'input' to 'build':
inputToBuild:
	rsync -va ${IN_DIR}/ ${BUILD_DIR}

# Remove the 'build' area:
clean: touch
	rm -rf ${BUILD_DIR}


