# This is the PyHPy Project Makefile.
# Adjust this Makefile to suit your server and project requirements.

# Find the location of this Makefile (this method works with 'make -C', but maybe not with 'make -f'.):
THIS_MAKEFILE=$(CURDIR)/$(word $(words $(MAKEFILE_LIST)),$(MAKEFILE_LIST))
MAKEFILE_DIR=$(patsubst %/,%,$(dir $(THIS_MAKEFILE)))

# We use the Makefile location to guess our project root:
PROJ_ROOT=${MAKEFILE_DIR}

# The location of PyHPy:
PYHPY_DIR=${PROJ_ROOT}/pyhpy

# Directory locations:
IN_DIR=${PROJ_ROOT}/input
BUILD_DIR=${PROJ_ROOT}/.build
OUT_DIR=${PROJ_ROOT}/output
OUT_DEV_DIR=${OUT_DIR}/dev
OUT_PROD_DIR_NAME=prod-$(shell date '+%Y%m%d%H%M%S')
OUT_PROD_DIR=${OUT_DIR}/${OUT_PROD_DIR_NAME}
OUT_PROD_SYMLINK=${OUT_DIR}/prod

# Build Options:
ACL_CHECK=1
AUTO_RM=0

# The port and docroot of the development HTTP server:
WWW_PORT=8000
WWW_DIR=${OUT_DEV_DIR}

# Commands that might need adjustment for your system:
PYTHON=python2.7
COPY=rsync -vaHAX --info=flist0,stats0
export PYTHONPATH:=${PYHPY_DIR}/lib/python:${PYTHONPATH}


# By default, build the development site without doing ACL checks, and with auto-remove enabled:
# The first two lines are target-specific variables (http://www.gnu.org/software/make/manual/html_node/Target_002dspecific.html).
dev-fast: ACL_CHECK=0
dev-fast: AUTO_RM=1
dev-fast: dev

# Build the development site:
dev:
	@echo
	${COPY} "${IN_DIR}/" "${BUILD_DIR}"
	@echo
	ACL_CHECK=${ACL_CHECK} AUTO_RM=${AUTO_RM} "${PYTHON}" "${PYHPY_DIR}/bin/pyhpy_build" "${BUILD_DIR}" "${OUT_DEV_DIR}"
	@echo
	@echo "DEV Built Successfully!  Output is at: ${OUT_DEV_DIR}"
	@echo

# Copy 'dev' to 'prod':
prod: dev
	${COPY} "${OUT_DEV_DIR}/" "${OUT_PROD_DIR}"
	@echo
	ln -sfn "${OUT_PROD_DIR_NAME}" "${OUT_PROD_SYMLINK}"
	@echo
	@echo "PROD Built Successfully!  Output is at: ${OUT_PROD_SYMLINK}"
	@echo

# Remove the 'build' area.  Also set the dev output's timestamps in the past so that everything will get re-built next time:
clean:
	rm -rf "${BUILD_DIR}"
	find "${OUT_DEV_DIR}" -type f -exec touch -t 198607060000 '{}' ';'

# Useful for local development and testing:
server:
	"${PYTHON}" -m pyhpy.httpd "${WWW_PORT}" "${WWW_DIR}"


