#!/bin/bash
# Written by Christopher Sebastian, 2011-12-14
###########################################################
# set -o errexit   # Abort script if there is an error    #
# set -o nounset   # Using an un-set variable is an error #
# set -x           # Trace                                #
if [ "$(id -u)" != "0" ]; then                            #
    echo 'You should be root to run this.' ; exit 1       #
fi                                                        #
MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" #
RUNNING_FILE="${MYDIR}000_RUNNING"                        #
IS_RUNNING=0                                              #
if [ -f "$RUNNING_FILE" ]; then IS_RUNNING=1 ; fi         #
export CHROOT_DIR="$MYDIR/ROOT"                           #
if [ ! -d "$CHROOT_DIR" ]; then                           #
    echo "Error: CHROOT_DIR does not exist: $CHROOT_DIR"  #
    exit 1;                                               #
fi                                                        #
###########################################################


# Make the 'RUNNING' file (just in case this gets run separately from 'start'):
touch "$RUNNING_FILE"
chmod 777 "$RUNNING_FILE"  # For colors in LS listings.

# Do the mount:
"$MYDIR/recursive_mount" mount / "$CHROOT_DIR/mnt/host"

