#!/bin/bash
# Written by Christopher Sebastian, 2011-12-14
###########################################################
# set -o errexit   # Abort script if there is an error    #
# set -o nounset   # Using an un-set variable is an error #
# set -x           # Trace                                #
if [ "$(id -u)" != "0" ]; then                            #
    echo 'You should be root to run this.' ; exit 1       #
fi                                                        #
MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" #
RUNNING_FILE="${MYDIR}000_RUNNING"                        #
IS_RUNNING=0                                              #
if [ -f "$RUNNING_FILE" ]; then IS_RUNNING=1 ; fi         #
export CHROOT_DIR="$MYDIR/ROOT"                           #
if [ ! -d "$CHROOT_DIR" ]; then                           #
    echo "Error: CHROOT_DIR does not exist: $CHROOT_DIR"  #
    exit 1;                                               #
fi                                                        #
###########################################################


### Updates and Downloads: ###
function download {
    fname="$1"
    echo "Downloading ${fname}..."
    wget -q -O "$MYDIR/.downloading" "http://nomake.org/code/$fname?nocache=$(date '+%s')";
    result=$?
    if [ "$result" != 0 ]; then return $result; fi
    mv "$MYDIR/.downloading" "$MYDIR/$fname"
    if [ "$fname" != "README.txt" ]; then chmod a+x "$MYDIR/$fname"; fi
    return 0
}
if [ "${FORCE_UPDATE:-0}" = 1 ]; then
    download start
    result=$?
    if [ "$result" != 0 ]; then
        echo 'Update Failed!  Aborting.'
        exit 1
    fi
    for x in README.txt run stop recursive_mount mount_host umount_host; do #### S
        if [ -f "$MYDIR/$x" ]; then mv "$MYDIR/$x" "$MYDIR/.${x}_old"; fi      # A
    done                                                                       # M
    FORCE_UPDATE=0 "$MYDIR/start"   # Re-launch new version.                   # EF
    result=$?                                                                  #  I
    exit $result                                                               #  L
fi                                                                             #  E
for x in README.txt run stop recursive_mount mount_host umount_host; do ########  S
    if [ ! -f "$MYDIR/$x" ]; then download "$x"; fi
done


### Make the 'RUNNING' file: ###
touch "$RUNNING_FILE"
chmod 777 "$RUNNING_FILE"  # For colors in LS listings.


### Core mounts: ###
"$MYDIR/recursive_mount" mount /dev "$CHROOT_DIR/dev"
"$MYDIR/recursive_mount" mount /proc "$CHROOT_DIR/proc"
"$MYDIR/recursive_mount" mount /sys "$CHROOT_DIR/sys"
"$MYDIR/recursive_mount" mount /tmp "$CHROOT_DIR/tmp"


### Host mounts: ###
if [ "${MOUNT_HOST:-0}" = 1 ]; then
    ./mount_host
fi


### Boot script: ###
if [ "$IS_RUNNING" = 0  -o  "${FORCE_BOOT:-0}" = 1 ]; then
    "$MYDIR/run" /nomake/boot.sh
else
    echo 'Already started.'
fi

